package com.buttoncode.mstest.admin.security;

public class SecurityUtil
{
	public static final String MANAGE_ACCOUNT = "ROLE_ACCOUNT";

	public static final String MANAGE_COMPLIANCES = "ROLE_MANAGE_COMPLIANCES";
	public static final String MANAGE_COMPLIANCES_CODE_OF_ETHIC = "ROLE_MANAGE_COMPLIANCES_CODE_OF_ETHIC";
	public static final String MANAGE_COMPLIANCES_ANTICORRUPTION_POLICY = "ROLE_MANAGE_COMPLIANCES_ANTICORRUPTION_POLICY";

	public static final String MANAGE_DEPARTMENT = "ROLE_MANAGE_DEPARTMENT";

	public static final String MANAGE_EMPLOYEES = "ROLE_MANAGE_EMPLOYEES";
	public static final String MANAGE_EMPLOYEES_WITHOUT = "ROLE_MANAGE_EMPLOYEES_WITHOUT";
	public static final String MANAGE_EMPLOYEES_ADDEMPLOYEE = "ROLE_MANAGE_EMPLOYEES_ADDEMPLOYEE";
	public static final String MANAGE_EMPLOYEES_UPLOADEMPLOYEE = "ROLE_MANAGE_EMPLOYEES_ADDEMPLOYEE";
	public static final String MANAGE_EMPLOYEES_TASKBOOK = "ROLE_MANAGE_EMPLOYEES_TASKBOOK";
	public static final String MANAGE_EMPLOYEES_EDITEMPLOYEE = "ROLE_MANAGE_EMPLOYEES_EDITEMPLOYEE";

	public static final String MANAGE_USERS = "ROLE_MANAGE_USERS";
	public static final String MANAGE_ROLES = "ROLE_MANAGE_ROLES";
	public static final String MANAGE_PERMISSIONS = "ROLE_MANAGE_PERMISSIONS";
}
